import { z } from "zod";

import { SupportedCurrencyEnum, ThreeDsStatusEnum, TransactionStatusEnum } from "./enums";

export const CallbackResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    status: TransactionStatusEnum,
    statusCode: z.string().meta({
      description: "Transaction status code.",
    }),
    statusMessage: z.string().meta({
      description: "Transaction status information message.",
    }),
    threeDs: ThreeDsStatusEnum.optional().meta({
      description: "3-D Secure authentication result (e.g. `AUTHENTICATED`).",
    }),
    rrn: z.string().optional().meta({
      description: "RRN — transaction ID generated by maib.",
    }),
    approval: z.string().optional().meta({
      description: "Approval code issued by the card issuing bank.",
    }),
    cardNumber: z.string().optional().meta({
      description: "Masked card number.",
    }),
    amount: z.number().nonnegative().optional().meta({
      description: "Transaction amount. Format: `X.XX`.",
    }),
    currency: SupportedCurrencyEnum.optional(),
    billerId: z.string().optional().meta({
      description:
        "Card identifier saved in the maib ecomm system (present for savecard-recurring / savecard-oneclick callbacks).",
    }),
    billerExpiry: z
      .string()
      .regex(/^\d{4}$/)
      .optional()
      .meta({
        description:
          "Stored-card expiry cutoff. Format: `MMYY` (present for savecard-recurring / savecard-oneclick callbacks).",
      }),
  })
  .meta({
    id: "maib.ecommerce.CallbackResult",
    description: "Transaction data embedded in a `CallbackPayload`.",
  });

export const CallbackPayloadSchema = z
  .looseObject({
    // Reference the registered CallbackResultSchema directly — wrapping with
    // .meta() would create an unregistered clone and break the cross-schema
    // $ref in the emitted JSON Schema.
    result: CallbackResultSchema,
    signature: z.string().meta({
      description:
        "Signature for integrity verification. Computed as `Base64(sha256(Implode(Sort(params) + signatureKey, ':')))`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.CallbackPayload",
    description: "Callback notification envelope delivered to the merchant's callback URL.",
  });
