import { z } from "zod";

import { LanguageEnum, SupportedCurrencyEnum } from "./enums";

/** A line item included in a payment request. */
export const PaymentItemSchema = z
  .looseObject({
    id: z.string().max(36).optional().meta({
      description: "Product ID (max 36 chars).",
    }),
    name: z.string().max(128).optional().meta({
      description: "Product name (max 128 chars).",
    }),
    price: z.number().positive().optional().meta({
      description: "Product price, in major currency units. Format: `X.XX`.",
    }),
    quantity: z.int().positive().optional().meta({
      description: "Product quantity.",
    }),
  })
  .meta({
    id: "maib.ecommerce.PaymentItem",
    description: "A line item included in a payment request.",
  });

/**
 * Fields shared by all customer-facing payment requests. Inlined into each
 * concrete request schema rather than referenced via `$ref` to keep emitted
 * JSON Schema self-contained per shape.
 */
export const basePaymentParamsShape = {
  description: z.string().max(124).optional().meta({
    description: "Payment description. Displayed on the maib ecomm checkout page (max 124 chars).",
  }),
  clientName: z.string().max(128).optional().meta({
    description: "Customer name (max 128 chars).",
  }),
  email: z.email().max(40).optional().meta({
    description: "Customer email (max 40 chars).",
  }),
  phone: z.string().max(40).optional().meta({
    description: "Customer phone (max 40 chars).",
  }),
  orderId: z.string().max(36).optional().meta({
    description: "Order ID generated by the merchant website/app (max 36 chars).",
  }),
  delivery: z.number().nonnegative().optional().meta({
    description: "Shipping cost in major currency units. Format: `X.XX`.",
  }),
  items: z.array(PaymentItemSchema).max(50).optional().meta({
    description: "Products or services ordered (max 50 items).",
  }),
  callbackUrl: z.url().max(2048).optional().meta({
    description:
      "URL where the merchant receives the final transaction result. Falls back to the project's Callback URL configured in maibmerchants if not provided (max 2048 chars).",
  }),
  okUrl: z.url().max(2048).optional().meta({
    description:
      "URL where the customer is redirected after a successful transaction. Falls back to the project's OK URL configured in maibmerchants if not provided (max 2048 chars).",
  }),
  failUrl: z.url().max(2048).optional().meta({
    description:
      "URL where the customer is redirected after a failed transaction. Falls back to the project's Fail URL configured in maibmerchants if not provided (max 2048 chars).",
  }),
} as const;

/** Mixin: required customer-facing init fields. */
export const customerFacingParamsShape = {
  clientIp: z.ipv4().meta({
    description: "Customer IPv4 address.",
  }),
  language: LanguageEnum,
  currency: SupportedCurrencyEnum,
} as const;

/**
 * Standalone schema for {@link basePaymentParamsShape} so consumers reading
 * `schemas.json` can find the mixin under a stable id.
 */
export const BasePaymentParamsSchema = z.object(basePaymentParamsShape).meta({
  id: "maib.ecommerce.BasePaymentParams",
  description: "Shared optional fields for customer-facing payment requests.",
});

/**
 * Standalone schema for {@link customerFacingParamsShape} so consumers reading
 * `schemas.json` can find the mixin under a stable id.
 */
export const CustomerFacingParamsSchema = z.object(customerFacingParamsShape).meta({
  id: "maib.ecommerce.CustomerFacingParams",
  description: "Required fields for customer-facing payment init requests.",
});
