import { z } from "zod";

import { basePaymentParamsShape, customerFacingParamsShape, PaymentItemSchema } from "./common";
import { SupportedCurrencyEnum } from "./enums";

export const PayRequestSchema = z
  .object({
    ...basePaymentParamsShape,
    ...customerFacingParamsShape,
    amount: z.number().min(1).meta({
      description: "Transaction amount in major currency units (≥ 1). Format: `X.XX`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.PayRequest",
    description: "Request body for `EcommerceClient.pay`.",
  });

export const HoldRequestSchema = z
  .object({
    ...basePaymentParamsShape,
    ...customerFacingParamsShape,
    amount: z.number().min(1).meta({
      description: "Amount to put on hold on the customer's account (≥ 1). Format: `X.XX`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.HoldRequest",
    description: "Request body for `EcommerceClient.hold`.",
  });

export const CompleteRequestSchema = z
  .object({
    payId: z.string().min(1).meta({
      description: "Identifier of the transaction that was authorized and must be captured.",
    }),
    confirmAmount: z.number().positive().optional().meta({
      description:
        "Amount to debit from the customer's account. Format: `X.XX`. Must be less than or equal to the previously held amount. If omitted, the full held amount is debited.",
    }),
  })
  .meta({
    id: "maib.ecommerce.CompleteRequest",
    description: "Request body for `EcommerceClient.complete`.",
  });

export const RefundRequestSchema = z
  .object({
    payId: z.string().min(1).meta({
      description: "Identifier of the transaction to be refunded.",
    }),
    refundAmount: z.number().positive().optional().meta({
      description:
        "Amount to return to the customer. Format: `X.XX`. Must be less than or equal to the transaction amount. If omitted, the full transaction amount is refunded.",
    }),
  })
  .meta({
    id: "maib.ecommerce.RefundRequest",
    description: "Request body for `EcommerceClient.refund`.",
  });

export const SavecardRecurringRequestSchema = z
  .object({
    ...basePaymentParamsShape,
    ...customerFacingParamsShape,
    billerExpiry: z
      .string()
      .regex(/^\d{4}$/)
      .meta({
        description:
          "Card expiry cutoff for stored card data. Format: `MMYY` (e.g. `1229` → 31 December 2029). If the card itself expires earlier, the card's own expiry is used.",
      }),
    email: z.email().max(40).meta({
      description: "Customer email (required for recurring).",
    }),
    amount: z.number().positive().optional().meta({
      description:
        "Transaction amount in major currency units. Format: `X.XX`. If provided, the amount is debited and the card is stored. If omitted, only the card is stored (no debit).",
    }),
  })
  .meta({
    id: "maib.ecommerce.SavecardRecurringRequest",
    description: "Request body for `EcommerceClient.savecardRecurring`.",
  });

export const ExecuteRecurringRequestSchema = z
  .object({
    billerId: z.string().min(1).meta({
      description: "Identifier of the previously stored card (`billerId`).",
    }),
    amount: z.number().positive().meta({
      description: "Transaction amount in major currency units. Format: `X.XX`.",
    }),
    currency: SupportedCurrencyEnum,
    description: z.string().max(124).optional().meta({
      description: "Payment description (max 124 chars).",
    }),
    orderId: z.string().max(36).optional().meta({
      description: "Order ID generated by the merchant website/app (max 36 chars).",
    }),
    delivery: z.number().nonnegative().optional().meta({
      description: "Shipping cost. Format: `X.XX`.",
    }),
    items: z.array(PaymentItemSchema).max(50).optional().meta({
      description: "Products or services ordered (max 50 items).",
    }),
  })
  .meta({
    id: "maib.ecommerce.ExecuteRecurringRequest",
    description: "Request body for `EcommerceClient.executeRecurring`.",
  });

export const SavecardOneclickRequestSchema = z
  .object({
    ...basePaymentParamsShape,
    ...customerFacingParamsShape,
    billerExpiry: z
      .string()
      .regex(/^\d{4}$/)
      .meta({
        description:
          "Card expiry cutoff for stored card data. Format: `MMYY` (e.g. `1229` → 31 December 2029).",
      }),
    amount: z.number().positive().optional().meta({
      description:
        "Transaction amount. Format: `X.XX`. If provided, the amount is debited and the card is stored. If omitted, only the card is stored (no debit).",
    }),
  })
  .meta({
    id: "maib.ecommerce.SavecardOneclickRequest",
    description: "Request body for `EcommerceClient.savecardOneclick`.",
  });

export const ExecuteOneclickRequestSchema = z
  .object({
    ...basePaymentParamsShape,
    ...customerFacingParamsShape,
    billerId: z.string().min(1).meta({
      description: "Identifier of the previously stored card (`billerId`).",
    }),
    amount: z.number().positive().meta({
      description: "Transaction amount. Format: `X.XX`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.ExecuteOneclickRequest",
    description: "Request body for `EcommerceClient.executeOneclick`.",
  });
