import { z } from "zod";

import { TransactionStatus } from "../constants";
import { PaymentItemSchema } from "./common";
import { SupportedCurrencyEnum, ThreeDsStatusEnum, TransactionStatusEnum } from "./enums";

export const PaymentInitResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    payUrl: z.url().meta({
      description: "URL of the maib ecomm checkout page to redirect the customer to.",
    }),
  })
  .meta({
    id: "maib.ecommerce.PaymentInitResult",
    description: "Intermediate result returned by payment init endpoints.",
  });

export const CompleteResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    status: TransactionStatusEnum.meta({
      description: "Transaction status (e.g. `OK`).",
    }),
    statusCode: z.string().meta({
      description: "Transaction status code.",
    }),
    statusMessage: z.string().meta({
      description: "Transaction status information message.",
    }),
    rrn: z.string().optional().meta({
      description: "RRN — transaction ID generated by maib ecomm.",
    }),
    approval: z.string().optional().meta({
      description: "Approval code issued by the card issuing bank.",
    }),
    cardNumber: z.string().optional().meta({
      description: "Masked card number.",
    }),
    confirmAmount: z.number().nonnegative().meta({
      description: "Amount debited from the customer's account. Format: `X.XX`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.CompleteResult",
    description: "Final result returned by `EcommerceClient.complete`.",
  });

export const RefundResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    status: z.enum([TransactionStatus.OK, TransactionStatus.REVERSED]).meta({
      description:
        "Refund status: `OK` — successfully refunded; `REVERSED` — already refunded previously, repeat not allowed.",
    }),
    statusCode: z.string().meta({
      description: "Transaction status code.",
    }),
    statusMessage: z.string().meta({
      description: "Transaction status information message.",
    }),
    refundAmount: z.number().nonnegative().meta({
      description: "Amount returned to the customer. Format: `X.XX`.",
    }),
  })
  .meta({
    id: "maib.ecommerce.RefundResult",
    description: "Final result returned by `EcommerceClient.refund`.",
  });

export const PayInfoResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    billerId: z.string().optional().meta({
      description:
        "Card identifier saved in the maib ecomm system (for recurring/one-click payments).",
    }),
    billerExpiry: z
      .string()
      .regex(/^\d{4}$/)
      .optional()
      .meta({
        description:
          "Stored-card expiry cutoff. Format: `MMYY` (for recurring/one-click payments).",
      }),
    status: TransactionStatusEnum,
    statusCode: z.string().meta({
      description: "Transaction status code.",
    }),
    statusMessage: z.string().meta({
      description: "Transaction status information message.",
    }),
    threeDs: ThreeDsStatusEnum.optional().meta({
      description: "3-D Secure authentication result (e.g. `AUTHENTICATED`).",
    }),
    rrn: z.string().optional().meta({
      description: "RRN — transaction ID generated by maib.",
    }),
    approval: z.string().optional().meta({
      description: "Approval code issued by the card issuing bank.",
    }),
    cardNumber: z.string().optional().meta({
      description: "Masked card number.",
    }),
    amount: z.number().nonnegative().meta({
      description: "Transaction amount. Format: `X.XX`.",
    }),
    confirmAmount: z.number().nonnegative().optional().meta({
      description:
        "Amount debited from the customer's account (for two-step payments). Format: `X.XX`.",
    }),
    refundAmount: z.number().nonnegative().optional().meta({
      description: "Amount refunded to the customer (for refunded payments). Format: `X.XX`.",
    }),
    currency: SupportedCurrencyEnum,
    description: z.string().optional().meta({
      description: "Payment description.",
    }),
    clientIp: z.ipv4().optional().meta({
      description: "Customer IPv4 address.",
    }),
    email: z.email().optional().meta({
      description: "Customer email.",
    }),
    phone: z.string().optional().meta({
      description: "Customer phone.",
    }),
    clientName: z.string().optional().meta({
      description: "Customer name.",
    }),
    delivery: z.number().nonnegative().optional().meta({
      description: "Shipping cost. Format: `X.XX`.",
    }),
    items: z.array(PaymentItemSchema).optional().meta({
      description: "Products or services ordered.",
    }),
  })
  .meta({
    id: "maib.ecommerce.PayInfoResult",
    description: "Details returned by `EcommerceClient.getPayInfo`.",
  });

export const ExecuteRecurringResultSchema = z
  .looseObject({
    payId: z.string().meta({
      description: "Transaction identifier assigned by maib ecomm.",
    }),
    billerId: z.string().meta({
      description: "Card identifier saved in the maib ecomm system.",
    }),
    orderId: z.string().optional().meta({
      description: "Order ID generated by the merchant website/app.",
    }),
    status: TransactionStatusEnum.meta({
      description: "Transaction status (e.g. `OK`).",
    }),
    statusCode: z.string().meta({
      description: "Transaction status code.",
    }),
    statusMessage: z.string().meta({
      description: "Transaction status information message.",
    }),
    rrn: z.string().optional().meta({
      description: "RRN — transaction ID generated by maib.",
    }),
    approval: z.string().optional().meta({
      description: "Approval code issued by the card issuing bank.",
    }),
    cardNumber: z.string().optional().meta({
      description: "Masked card number.",
    }),
    amount: z.number().nonnegative().meta({
      description: "Transaction amount. Format: `X.XX`.",
    }),
    currency: SupportedCurrencyEnum,
  })
  .meta({
    id: "maib.ecommerce.ExecuteRecurringResult",
    description: "Final result returned by `EcommerceClient.executeRecurring`.",
  });
