import type { Currency, MaibClientConfig } from "@maib/core";

/**
 * Configuration for the e-Commerce client.
 *
 * The `environment` option is excluded because the v1 E-Commerce API
 * is only available in the production environment.
 */
export interface EcommerceClientConfig
  extends Omit<MaibClientConfig, "clientId" | "clientSecret" | "environment"> {
  /** Project ID from the maibmerchants portal. */
  projectId: string;
  /** Project secret from the maibmerchants portal. */
  projectSecret: string;
}

/** A line item included in a payment request. */
export interface PaymentItem {
  /** Product ID (max 36 chars). */
  id?: string;
  /** Product name (max 128 chars). */
  name?: string;
  /** Product price, in major currency units. Format: `X.XX`. */
  price?: number;
  /** Product quantity. */
  quantity?: number;
}

/** Shared optional fields for customer-facing payment requests. */
export interface BasePaymentParams {
  /** Payment description. Displayed on the maib ecomm checkout page (max 124 chars). */
  description?: string;
  /** Customer name (max 128 chars). */
  clientName?: string;
  /** Customer email (max 40 chars). */
  email?: string;
  /** Customer phone (max 40 chars). */
  phone?: string;
  /** Order ID generated by the merchant website/app (max 36 chars). */
  orderId?: string;
  /** Shipping cost in major currency units. Format: `X.XX`. */
  delivery?: number;
  /** Products or services ordered (max 50 items). */
  items?: PaymentItem[];
  /**
   * URL where the merchant receives the final transaction result.
   * Falls back to the project's Callback URL configured in maibmerchants
   * if not provided (max 2048 chars).
   */
  callbackUrl?: string;
  /**
   * URL where the customer is redirected after a successful transaction.
   * Falls back to the project's OK URL configured in maibmerchants
   * if not provided (max 2048 chars).
   */
  okUrl?: string;
  /**
   * URL where the customer is redirected after a failed transaction.
   * Falls back to the project's Fail URL configured in maibmerchants
   * if not provided (max 2048 chars).
   */
  failUrl?: string;
}

/** Required fields for customer-facing payment init requests. */
export interface CustomerFacingParams {
  /** Customer IP (IPv4). */
  clientIp: string;
  /** Checkout page language. Allowed values: `ro`, `en`, `ru`. */
  language: string;
  /** Transaction currency (`MDL` / `EUR` / `USD`). */
  currency: Currency;
}

// -----------------------------------------------------------------------
// Request types
// -----------------------------------------------------------------------

/** Request body for {@link EcommerceClient.pay}. */
export interface PayRequest extends BasePaymentParams, CustomerFacingParams {
  /** Transaction amount in major currency units (≥ 1). Format: `X.XX`. */
  amount: number;
}

/** Request body for {@link EcommerceClient.hold}. */
export interface HoldRequest extends BasePaymentParams, CustomerFacingParams {
  /** Amount to put on hold on the customer's account (≥ 1). Format: `X.XX`. */
  amount: number;
}

/** Request body for {@link EcommerceClient.complete}. */
export interface CompleteRequest {
  /** Identifier of the transaction that was authorized and must be captured. */
  payId: string;
  /**
   * Amount to debit from the customer's account. Format: `X.XX`.
   * Must be less than or equal to the previously held amount.
   * If omitted, the full held amount is debited.
   */
  confirmAmount?: number;
}

/** Request body for {@link EcommerceClient.refund}. */
export interface RefundRequest {
  /** Identifier of the transaction to be refunded. */
  payId: string;
  /**
   * Amount to return to the customer. Format: `X.XX`.
   * Must be less than or equal to the transaction amount.
   * If omitted, the full transaction amount is refunded.
   */
  refundAmount?: number;
}

/** Request body for {@link EcommerceClient.savecardRecurring}. */
export interface SavecardRecurringRequest extends BasePaymentParams, CustomerFacingParams {
  /**
   * Card expiry cutoff for stored card data. Format: `MMYY`
   * (e.g. `1229` → 31 December 2029). If the card itself expires earlier,
   * the card's own expiry is used.
   */
  billerExpiry: string;
  /** Customer email (required for recurring). */
  email: string;
  /**
   * Transaction amount in major currency units. Format: `X.XX`.
   * If provided, the amount is debited and the card is stored.
   * If omitted, only the card is stored (no debit).
   */
  amount?: number;
}

/** Request body for {@link EcommerceClient.executeRecurring}. */
export interface ExecuteRecurringRequest {
  /** Identifier of the previously stored card (`billerId`). */
  billerId: string;
  /** Transaction amount in major currency units. Format: `X.XX`. */
  amount: number;
  /** Transaction currency (`MDL` / `EUR` / `USD`). */
  currency: Currency;
  /** Payment description (max 124 chars). */
  description?: string;
  /** Order ID generated by the merchant website/app (max 36 chars). */
  orderId?: string;
  /** Shipping cost. Format: `X.XX`. */
  delivery?: number;
  /** Products or services ordered (max 50 items). */
  items?: PaymentItem[];
}

/** Request body for {@link EcommerceClient.savecardOneclick}. */
export interface SavecardOneclickRequest extends BasePaymentParams, CustomerFacingParams {
  /**
   * Card expiry cutoff for stored card data. Format: `MMYY`
   * (e.g. `1229` → 31 December 2029).
   */
  billerExpiry: string;
  /**
   * Transaction amount. Format: `X.XX`.
   * If provided, the amount is debited and the card is stored.
   * If omitted, only the card is stored (no debit).
   */
  amount?: number;
}

/** Request body for {@link EcommerceClient.executeOneclick}. */
export interface ExecuteOneclickRequest extends BasePaymentParams, CustomerFacingParams {
  /** Identifier of the previously stored card (`billerId`). */
  billerId: string;
  /** Transaction amount. Format: `X.XX`. */
  amount: number;
}

// -----------------------------------------------------------------------
// Response types
// -----------------------------------------------------------------------

/** Intermediate result returned by payment init endpoints. */
export interface PaymentInitResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /** URL of the maib ecomm checkout page to redirect the customer to. */
  payUrl: string;
}

/** Final result returned by {@link EcommerceClient.complete}. */
export interface CompleteResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /** Transaction status (e.g. `OK`). */
  status: string;
  /** Transaction status code. */
  statusCode: string;
  /** Transaction status information message. */
  statusMessage: string;
  /** RRN — transaction ID generated by maib ecomm. */
  rrn?: string;
  /** Approval code issued by the card issuing bank. */
  approval?: string;
  /** Masked card number. */
  cardNumber?: string;
  /** Amount debited from the customer's account. Format: `X.XX`. */
  confirmAmount: number;
}

/** Final result returned by {@link EcommerceClient.refund}. */
export interface RefundResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /**
   * Refund status:
   * `OK` — successfully refunded;
   * `REVERSED` — already refunded previously, repeat not allowed.
   */
  status: string;
  /** Transaction status code. */
  statusCode: string;
  /** Transaction status information message. */
  statusMessage: string;
  /** Amount returned to the customer. Format: `X.XX`. */
  refundAmount: number;
}

/** Details returned by {@link EcommerceClient.getPayInfo}. */
export interface PayInfoResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /**
   * Card identifier saved in the maib ecomm system
   * (for recurring/one-click payments).
   */
  billerId?: string;
  /**
   * Stored-card expiry cutoff. Format: `MMYY`
   * (for recurring/one-click payments).
   */
  billerExpiry?: string;
  /**
   * Transaction status. Possible values:
   * `OK`, `FAILED`, `CREATED`, `PENDING`, `DECLINED`, `TIMEOUT`.
   */
  status: string;
  /** Transaction status code. */
  statusCode: string;
  /** Transaction status information message. */
  statusMessage: string;
  /** 3-D Secure authentication result (e.g. `AUTHENTICATED`). */
  threeDs?: string;
  /** RRN — transaction ID generated by maib. */
  rrn?: string;
  /** Approval code issued by the card issuing bank. */
  approval?: string;
  /** Masked card number. */
  cardNumber?: string;
  /** Transaction amount. Format: `X.XX`. */
  amount: number;
  /**
   * Amount debited from the customer's account (for two-step payments).
   * Format: `X.XX`.
   */
  confirmAmount?: number;
  /**
   * Amount refunded to the customer (for refunded payments).
   * Format: `X.XX`.
   */
  refundAmount?: number;
  /** Transaction currency (`MDL` / `EUR` / `USD`). */
  currency: Currency | (string & {});
  /** Payment description. */
  description?: string;
  /** Customer IP. */
  clientIp?: string;
  /** Customer email. */
  email?: string;
  /** Customer phone. */
  phone?: string;
  /** Customer name. */
  clientName?: string;
  /** Shipping cost. Format: `X.XX`. */
  delivery?: number;
  /** Products or services ordered. */
  items?: PaymentItem[];
}

/** Final result returned by {@link EcommerceClient.executeRecurring}. */
export interface ExecuteRecurringResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Card identifier saved in the maib ecomm system. */
  billerId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /** Transaction status (e.g. `OK`). */
  status: string;
  /** Transaction status code. */
  statusCode: string;
  /** Transaction status information message. */
  statusMessage: string;
  /** RRN — transaction ID generated by maib. */
  rrn?: string;
  /** Approval code issued by the card issuing bank. */
  approval?: string;
  /** Masked card number. */
  cardNumber?: string;
  /** Transaction amount. Format: `X.XX`. */
  amount: number;
  /** Transaction currency (`MDL` / `EUR` / `USD`). */
  currency: Currency | (string & {});
}

/** Callback notification envelope delivered to the merchant's callback URL. */
export interface CallbackPayload {
  /** Transaction result object. */
  result: CallbackResult;
  /**
   * Signature for integrity verification.
   * Computed as `Base64(sha256(Implode(Sort(params) + signatureKey, ':')))`.
   */
  signature: string;
}

/** Transaction data embedded in a {@link CallbackPayload}. */
export interface CallbackResult {
  /** Transaction identifier assigned by maib ecomm. */
  payId: string;
  /** Order ID generated by the merchant website/app. */
  orderId?: string;
  /**
   * Transaction status. Possible values:
   * `OK`, `FAILED`, `CREATED`, `PENDING`, `DECLINED`, `TIMEOUT`.
   */
  status: string;
  /** Transaction status code. */
  statusCode: string;
  /** Transaction status information message. */
  statusMessage: string;
  /** 3-D Secure authentication result (e.g. `AUTHENTICATED`). */
  threeDs?: string;
  /** RRN — transaction ID generated by maib. */
  rrn?: string;
  /** Approval code issued by the card issuing bank. */
  approval?: string;
  /** Masked card number. */
  cardNumber?: string;
  /** Transaction amount. Format: `X.XX`. */
  amount?: number;
  /** Transaction currency (`MDL` / `EUR` / `USD`). */
  currency?: Currency | (string & {});
  /**
   * Card identifier saved in the maib ecomm system
   * (present for savecard-recurring / savecard-oneclick callbacks).
   */
  billerId?: string;
  /**
   * Stored-card expiry cutoff. Format: `MMYY`
   * (present for savecard-recurring / savecard-oneclick callbacks).
   */
  billerExpiry?: string;
}
