import { describe, expect, it } from "vitest";

// @ts-expect-error untyped .mjs script, imported for testable internals
import { parseCurrencies, render } from "../../../scripts/generate-iso-4217.mjs";

/**
 * Synthetic list-one.xml snippet shaped after the real SIX Group document.
 * Exercises: (a) deduplication by Ccy code across multiple country entries,
 * (b) IsFund attribute capture, (c) "N.A." → null for non-currency metals,
 * (d) integer parsing of CcyMnrUnts, (e) sort-by-code ordering.
 */
const FIXTURE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<ISO_4217 Pblshd="2025-03-31">
  <CcyTbl>
    <CcyNtry>
      <CtryNm>MOLDOVA</CtryNm>
      <CcyNm>Moldovan Leu</CcyNm>
      <Ccy>MDL</Ccy>
      <CcyNbr>498</CcyNbr>
      <CcyMnrUnts>2</CcyMnrUnts>
    </CcyNtry>
    <CcyNtry>
      <CtryNm>FRANCE</CtryNm>
      <CcyNm>Euro</CcyNm>
      <Ccy>EUR</Ccy>
      <CcyNbr>978</CcyNbr>
      <CcyMnrUnts>2</CcyMnrUnts>
    </CcyNtry>
    <CcyNtry>
      <CtryNm>GERMANY</CtryNm>
      <CcyNm>Euro</CcyNm>
      <Ccy>EUR</Ccy>
      <CcyNbr>978</CcyNbr>
      <CcyMnrUnts>2</CcyMnrUnts>
    </CcyNtry>
    <CcyNtry>
      <CtryNm>ZZ08_Gold</CtryNm>
      <CcyNm IsFund="false">Gold</CcyNm>
      <Ccy>XAU</Ccy>
      <CcyNbr>959</CcyNbr>
      <CcyMnrUnts>N.A.</CcyMnrUnts>
    </CcyNtry>
    <CcyNtry>
      <CtryNm>SOME_FUND</CtryNm>
      <CcyNm IsFund="true">Sample Fund Unit</CcyNm>
      <Ccy>XFU</Ccy>
      <CcyNbr>999</CcyNbr>
      <CcyMnrUnts>0</CcyMnrUnts>
    </CcyNtry>
    <CcyNtry>
      <CtryNm>NO_CCY_LAND</CtryNm>
      <CcyNm>No universal currency</CcyNm>
      <CcyNbr/>
    </CcyNtry>
  </CcyTbl>
</ISO_4217>`;

describe("generate-iso-4217.mjs parseCurrencies", () => {
  it("captures the Pblshd attribute as the published date", () => {
    const result = parseCurrencies(FIXTURE_XML);
    expect(result.published).toBe("2025-03-31");
  });

  it("deduplicates by Ccy code (one entry per currency, not per country)", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const codes = result.currencies.map((c: { code: string }) => c.code);
    const eurEntries = codes.filter((c: string) => c === "EUR");
    expect(eurEntries).toHaveLength(1);
  });

  it("skips entries without a Ccy code (e.g. 'No universal currency')", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const names = result.currencies.map((c: { name: string }) => c.name);
    expect(names).not.toContain("No universal currency");
  });

  it("parses minor units as integers", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const mdl = result.currencies.find((c: { code: string }) => c.code === "MDL");
    expect(mdl?.minorUnits).toBe(2);
  });

  it("maps 'N.A.' minor units to null (precious metals have no subunit)", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const xau = result.currencies.find((c: { code: string }) => c.code === "XAU");
    expect(xau?.minorUnits).toBeNull();
  });

  it("captures IsFund=true when present, defaults to false otherwise", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const xfu = result.currencies.find((c: { code: string }) => c.code === "XFU");
    const mdl = result.currencies.find((c: { code: string }) => c.code === "MDL");
    expect(xfu?.isFund).toBe(true);
    expect(mdl?.isFund).toBe(false);
  });

  it("sorts currencies alphabetically by code", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const codes = result.currencies.map((c: { code: string }) => c.code);
    expect(codes).toEqual([...codes].sort());
  });

  it("returns an empty currency list for an XML with no CcyNtry entries", () => {
    const empty = `<?xml version="1.0" encoding="UTF-8"?><ISO_4217 Pblshd="2025-01-01"><CcyTbl></CcyTbl></ISO_4217>`;
    const result = parseCurrencies(empty);
    expect(result.currencies).toEqual([]);
    expect(result.published).toBe("2025-01-01");
  });
});

describe("generate-iso-4217.mjs render", () => {
  it("emits a TypeScript module with a const Currency object and matching type", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const output = render(result);
    expect(output).toMatch(/^\/\/ AUTOGENERATED from ISO 4217 list-one/m);
    expect(output).toMatch(/export const Currency = \{/);
    expect(output).toMatch(/} as const;/);
    expect(output).toMatch(/export type Currency = \(typeof Currency\)\[keyof typeof Currency\];/);
  });

  it("includes every parsed currency as a key/value pair", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const output = render(result);
    for (const { code } of result.currencies) {
      expect(output).toMatch(new RegExp(`\\b${code}: "${code}",`));
    }
  });

  it("labels fund entries with '(fund)' suffix in the JSDoc", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const output = render(result);
    expect(output).toMatch(/Sample Fund Unit \(fund\)/);
    // Non-fund entries don't get the suffix.
    expect(output).not.toMatch(/Moldovan Leu \(fund\)/);
  });

  it("embeds the published date and entry count in the header docstring", () => {
    const result = parseCurrencies(FIXTURE_XML);
    const output = render(result);
    expect(output).toMatch(/Published: 2025-03-31/);
    expect(output).toMatch(new RegExp(`Includes ${result.currencies.length} entries\\.`));
  });
});
